#
# Fred Cirera <fred@bsdhost.net>
#
# Home router deployment and management.
#
---
- name: Alix Home Router
  hosts: all
  pre_tasks:
    - shell: /bin/rw

  roles:
    - { role: base,     tags: base }
    - { role: pf,       tags: pf }
    - { role: ntpd,     tags: ntpd }
    - { role: dhcp,     tags: dhcp }
    - { role: unbound,  tags: unbound }
    - { role: sshd,     tags: sshd }

  post_tasks:
    - shell: /bin/ro
