#
# roles/tftp/tasks
#
---

- name: Creating the tftp tree
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    owner: root
    group: wheel
  with_items:
    - "/home/tftpboot.amd64"
    - "/home/tftpboot.i386"

- name: link to the default os version
  file:
    src: /home/tftpboot.amd64
    dest: /home/tftpboot
    state: link
    owner: root
    group: wheel

#- name: Downloading OpenBSD recover kernel.
#  get_url:
#    url: "{{ mirror_url }}/{{ item.arch }}/{{ item.file }}"
#    dest: "/home/tftpboot.{{ item.arch }}"
#    checksum: "sha256:{{ item.csum }}"
#    mode: 0444
#  with_items:
#    "{{ mirror_files }}"

- name: Enabling tftpd
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: "^#? *tftpd"
    line: 'tftpd_flags="-l {{ tftpd_interface }} /home/tftpboot"'
    create: True
    mode: 0644
    owner: root
  notify: restart tftpd
